packages:
  - packages/*
  - packages/*/*
  - playground
  - '!**/test/**'
catalogMode: prefer
cleanupUnusedCatalogs: true
catalog:
  '@antfu/eslint-config': ^6.2.0
  '@iconify-json/ri': ^1.2.6
  '@types/node': ^20.19.25
  '@unocss/reset': ^66.5.9
  '@vitejs/plugin-vue': ^6.0.2
  '@vitest/browser': ^4.0.13
  '@vue/reactivity': ^3.5.25
  '@vueuse/core': ^14.0.0
  '@webav/av-cliper': ^1.2.7
  '@webav/mp4box.js': 0.5.3-fenghen
  ajv: ^8.17.1
  ajv-errors: ^3.0.0
  ajv-formats: ^3.0.1
  ajv-keywords: ^5.1.0
  bumpp: ^10.3.1
  chalk: ^5.6.2
  eslint: ^9.39.1
  immer: ^11.0.0
  lint-staged: ^16.2.7
  opfs-tools: ^0.7.4
  pixi.js: ^8.14.3
  playwright: ^1.56.1
  simple-git-hooks: ^2.13.1
  typescript: ^5.9.3
  unocss: ^66.5.9
  unplugin-auto-import: ^20.2.0
  vite: ^7.2.4
  vite-plugin-dts: ^4.5.4
  vitest: ^4.0.13
  vue: ^3.5.25
  vue-tsc: ^3.1.5
